[tool.poetry]
name = "wizdiff"
version = "0.1.0"
description = ""
authors = ["StarrFox <starrfox6312@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.0.1"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
wizdiff = "wizdiff.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
